#!/bin/sh

echo "🔍 Running leaks checks before commit..."
make gitleaks

STATUS=$?

if [ $STATUS -ne 0 ]; then
  echo "❌ Leaks checks failed. Commit aborted."
  exit 1
fi

echo "✅ Pre-commit checks passed. Proceeding with commit."
exit 0
